import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';
import 'package:intl/intl.dart';

import '../../../../core/widgets/action_button.dart';
import '../../../../core/widgets/glass_text_field.dart';
import '../../../../theme/app_colors.dart';
import '../widgets/visitor_pass_card.dart';
import '../../../../core/repositories/visitor_repository.dart';
import '../../../../core/repositories/profile_repository.dart';

// State Management
final accessTabIndexProvider = StateProvider<int>((ref) => 0);

final myVisitorsProvider = AsyncNotifierProvider<MyVisitorsNotifier, List<Visitor>>(() => MyVisitorsNotifier());

class MyVisitorsNotifier extends AsyncNotifier<List<Visitor>> {
  @override
  Future<List<Visitor>> build() async {
    final profile = await ref.watch(currentProfileProvider.future);
    if (profile == null || profile.houseId == null) return [];
    
    final repo = ref.read(visitorRepositoryProvider);
    return repo.getVisitorsForHouse(profile.houseId!);
  }

  Future<void> refresh() async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() => build());
  }
}

class AccessPage extends ConsumerStatefulWidget {
  const AccessPage({super.key});

  @override
  ConsumerState<AccessPage> createState() => _AccessPageState();
}

class _AccessPageState extends ConsumerState<AccessPage> {
  final _nameController = TextEditingController();
  final _typeController = TextEditingController();
  final _dateController = TextEditingController();
  final _plateController = TextEditingController();
  bool _isSubmitting = false;

  @override
  void dispose() {
    _nameController.dispose();
    _typeController.dispose();
    _dateController.dispose();
    _plateController.dispose();
    super.dispose();
  }

  void _submitForm() async {
    if (_nameController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Visitor Name is required.')));
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      final profile = await ref.read(currentProfileProvider.future);
      if (profile == null || profile.houseId == null) {
        throw Exception('You must be assigned to a house to register visitors. Please contact Admin.');
      }

      final qrToken = 'v-${DateTime.now().millisecondsSinceEpoch}';
      
      final visitor = Visitor(
        id: '', // Will be generated by Supabase
        visitorName: _nameController.text,
        purpose: _typeController.text.isEmpty ? 'Guest' : _typeController.text,
        vehiclePlate: _plateController.text.isEmpty ? null : _plateController.text,
        houseId: profile.houseId!,
        qrToken: qrToken,
        status: 'pre-registered',
        expectedAt: DateTime.now().toIso8601String(), // Ideally from a date picker
        createdBy: profile.id,
        registrationType: 'pre_registered',
      );

      await ref.read(visitorRepositoryProvider).createVisitor(visitor);
      await ref.read(myVisitorsProvider.notifier).refresh();

      if (mounted) {
        _nameController.clear();
        _typeController.clear();
        _dateController.clear();
        _plateController.clear();
        ref.read(accessTabIndexProvider.notifier).state = 1; // Switch to passes tab
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.toString()), backgroundColor: Colors.red));
      }
    } finally {
      if (mounted) {
        setState(() => _isSubmitting = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final tabIndex = ref.watch(accessTabIndexProvider);

    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            Padding(
              padding: const EdgeInsets.fromLTRB(24, 32, 24, 24),
              child: _buildHeader(context),
            ),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 24),
              child: _buildSegmentedControl(tabIndex),
            ),
            const SizedBox(height: 24),
            Expanded(
              child: IndexedStack(
                index: tabIndex,
                children: [
                  _buildPreRegisterForm().animate(target: tabIndex == 0 ? 1 : 0).fade(duration: 300.ms).slideY(begin: 0.1, end: 0),
                  _buildActivePasses().animate(target: tabIndex == 1 ? 1 : 0).fade(duration: 300.ms).slideY(begin: 0.1, end: 0),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildHeader(BuildContext context) {
    final profileAsync = ref.watch(currentProfileProvider);
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        const Text(
          'Visitor Access',
          style: TextStyle(
            fontSize: 28,
            color: AppColors.textPrimary,
            fontWeight: FontWeight.bold,
          ),
        ),
        GestureDetector(
          onTap: () => context.push('/profile'),
          child: Container(
            width: 40,
            height: 40,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              border: Border.all(color: AppColors.primaryBlue.withOpacity(0.3), width: 1.5),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.05),
                  blurRadius: 8,
                  offset: const Offset(0, 2),
                )
              ],
            ),
            child: ClipOval(
              child: profileAsync.when(
                data: (profile) => profile?.avatarUrl != null 
                    ? Image.network(profile!.avatarUrl!, fit: BoxFit.cover)
                    : const Icon(PhosphorIconsRegular.user, color: AppColors.primaryBlue),
                loading: () => const CircularProgressIndicator(),
                error: (_, __) => const Icon(PhosphorIconsRegular.user, color: AppColors.primaryBlue),
              ),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildSegmentedControl(int currentIndex) {
    return Container(
      padding: const EdgeInsets.all(4),
      decoration: BoxDecoration(
        color: AppColors.primaryWhite.withOpacity(0.5),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: AppColors.glassBorder),
      ),
      child: Row(
        children: [
          Expanded(
            child: _buildSegmentButton(0, 'Pre-Register', currentIndex),
          ),
          Expanded(
            child: _buildSegmentButton(1, 'Active Passes', currentIndex),
          ),
        ],
      ),
    );
  }

  Widget _buildSegmentButton(int index, String label, int currentIndex) {
    final isSelected = index == currentIndex;
    return GestureDetector(
      onTap: () => ref.read(accessTabIndexProvider.notifier).state = index,
      behavior: HitTestBehavior.opaque,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        padding: const EdgeInsets.symmetric(vertical: 12),
        decoration: BoxDecoration(
          color: isSelected ? AppColors.primaryWhite : Colors.transparent,
          borderRadius: BorderRadius.circular(12),
          boxShadow: isSelected
              ? [BoxShadow(color: AppColors.shadowColor, blurRadius: 8, offset: const Offset(0, 2))]
              : [],
        ),
        child: Center(
          child: Text(
            label,
            style: TextStyle(
              fontSize: 14,
              fontWeight: isSelected ? FontWeight.w600 : FontWeight.w500,
              color: isSelected ? AppColors.textPrimary : AppColors.textSecondary,
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildPreRegisterForm() {
    return SingleChildScrollView(
      padding: const EdgeInsets.fromLTRB(24, 0, 24, 120),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          GlassTextField(
            controller: _nameController,
            hintText: 'Visitor Name',
            prefixIcon: PhosphorIconsRegular.user,
          ),
          const SizedBox(height: 16),
          GlassTextField(
            controller: _typeController,
            hintText: 'Purpose (e.g. Guest, Delivery)',
            prefixIcon: PhosphorIconsRegular.tag,
          ),
          const SizedBox(height: 16),
          GlassTextField(
            controller: _dateController,
            hintText: 'Date & Time (Optional)',
            prefixIcon: PhosphorIconsRegular.calendar,
          ),
          const SizedBox(height: 16),
          GlassTextField(
            controller: _plateController,
            hintText: 'Vehicle Plate (Optional)',
            prefixIcon: PhosphorIconsRegular.carProfile,
          ),
          const SizedBox(height: 32),
          _isSubmitting
              ? const Center(
                  child: CircularProgressIndicator(
                    color: AppColors.primaryBlue,
                  ),
                )
              : ActionButton(
                  label: 'Generate Pass',
                  onPressed: _submitForm,
                  backgroundColor: AppColors.primaryBlue,
                  icon: PhosphorIconsRegular.qrCode,
                ),
        ],
      ),
    );
  }

  Widget _buildActivePasses() {
    final visitorsAsync = ref.watch(myVisitorsProvider);

    return visitorsAsync.when(
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, stack) => Center(child: Text('Error: $error')),
      data: (visitors) {
        // Show only active passes (pre-registered or checked-in)
        final activeVisitors = visitors.where((v) => v.status != 'checked-out' && v.qrToken != null).toList();
        
        if (activeVisitors.isEmpty) {
          return const Center(
            child: Text('No active visitor passes.', style: TextStyle(color: Color(0xFFA3AED0))),
          );
        }

        return ListView.separated(
          padding: const EdgeInsets.fromLTRB(24, 0, 24, 120),
          itemCount: activeVisitors.length,
          separatorBuilder: (context, index) => const SizedBox(height: 16),
          itemBuilder: (context, index) {
            final visitor = activeVisitors[index];
            final dateStr = visitor.expectedAt != null 
                ? DateFormat('MMM d, yyyy HH:mm').format(DateTime.parse(visitor.expectedAt!).toLocal())
                : 'Walk-in';

            return VisitorPassCard(
              name: visitor.visitorName,
              type: visitor.purpose,
              time: dateStr,
              qrData: visitor.qrToken!,
            );
          },
        );
      },
    );
  }
}
