import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';
import 'package:intl/intl.dart';

import '../../../../core/widgets/action_button.dart';
import '../../../../core/widgets/app_states.dart';
import '../../../../core/widgets/glass_text_field.dart';
import '../../../../core/widgets/gradient_background.dart';
import '../../../../core/widgets/premium_card.dart';
import '../../../../core/widgets/section_header.dart';
import '../../../../theme/app_colors.dart';
import '../widgets/visitor_pass_card.dart';
import 'package:cached_network_image/cached_network_image.dart';
import '../../../../core/repositories/visitor_repository.dart';
import '../../../../core/repositories/profile_repository.dart';

// State Management
final accessTabIndexProvider = StateProvider<int>((ref) => 0);

final myVisitorsProvider =
    AsyncNotifierProvider<MyVisitorsNotifier, List<Visitor>>(
      () => MyVisitorsNotifier(),
    );

class MyVisitorsNotifier extends AsyncNotifier<List<Visitor>> {
  @override
  Future<List<Visitor>> build() async {
    final profile = await ref.watch(currentProfileProvider.future);
    if (profile == null || profile.houseId == null) return [];

    final repo = ref.read(visitorRepositoryProvider);
    return repo.getVisitorsForHouse(profile.houseId!);
  }

  Future<void> refresh() async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() => build());
  }
}

class AccessPage extends ConsumerStatefulWidget {
  const AccessPage({super.key});

  @override
  ConsumerState<AccessPage> createState() => _AccessPageState();
}

class _AccessPageState extends ConsumerState<AccessPage> {
  final _nameController = TextEditingController();
  final _typeController = TextEditingController();
  final _dateController = TextEditingController();
  final _plateController = TextEditingController();
  DateTime? _selectedDateTime;
  bool _isSubmitting = false;
  // HCA point 7: visitor pass entry type + its validity inputs.
  String _entryType = 'single'; // single | multiple | long_term
  DateTime? _validFrom;
  DateTime? _validTo;
  final List<DateTime> _visitDays = [];
  final _timeWindowController = TextEditingController();

  Future<void> _pickDateTime() async {
    final now = DateTime.now();
    final pickedDate = await showDatePicker(
      context: context,
      initialDate: _selectedDateTime ?? now,
      firstDate: now,
      lastDate: now.add(const Duration(days: 365)),
    );
    if (pickedDate == null || !mounted) return;

    final pickedTime = await showTimePicker(
      context: context,
      initialTime: TimeOfDay.fromDateTime(_selectedDateTime ?? now),
    );
    if (!mounted) return;

    final result = DateTime(
      pickedDate.year,
      pickedDate.month,
      pickedDate.day,
      pickedTime?.hour ?? 0,
      pickedTime?.minute ?? 0,
    );
    setState(() {
      _selectedDateTime = result;
      _dateController.text = DateFormat('MMM d, yyyy HH:mm').format(result);
    });
  }

  /// HCA multiple-entry passes: pick the daily time window from the clock
  /// (start time, then end time) instead of typing it.
  Future<void> _pickTimeWindow() async {
    final start = await showTimePicker(
      context: context,
      initialTime: const TimeOfDay(hour: 9, minute: 0),
      helpText: 'Select start time',
    );
    if (start == null || !mounted) return;

    final end = await showTimePicker(
      context: context,
      initialTime: TimeOfDay(hour: (start.hour + 3) % 24, minute: start.minute),
      helpText: 'Select end time',
    );
    if (end == null || !mounted) return;

    setState(() {
      _timeWindowController.text =
          '${start.format(context)} - ${end.format(context)}';
    });
  }

  @override
  void dispose() {
    _nameController.dispose();
    _typeController.dispose();
    _dateController.dispose();
    _plateController.dispose();
    _timeWindowController.dispose();
    super.dispose();
  }

  void _submitForm() async {
    if (_nameController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Visitor Name is required.')),
      );
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      final profile = await ref.read(currentProfileProvider.future);
      if (profile == null ||
          profile.houseId == null ||
          profile.houseId!.isEmpty) {
        throw Exception(
          'You must be assigned to a house to register visitors. Please contact Admin.',
        );
      }

      final qrToken = 'v-${DateTime.now().millisecondsSinceEpoch}';

      String d(DateTime x) =>
          '${x.year.toString().padLeft(4, '0')}-${x.month.toString().padLeft(2, '0')}-${x.day.toString().padLeft(2, '0')}';

      final visitor = Visitor(
        id: '', // Will be generated by Supabase
        visitorName: _nameController.text,
        purpose: _typeController.text.isEmpty ? 'Guest' : _typeController.text,
        vehiclePlate: _plateController.text.isEmpty
            ? null
            : _plateController.text,
        houseId: profile.houseId!,
        qrToken: qrToken,
        status: 'expected',
        expectedAt: (_selectedDateTime ?? DateTime.now()).toIso8601String(),
        createdBy: profile.id,
        registrationType: 'pre-registered',
        // Point 7 validity (HCA).
        entryType: _entryType,
        validFrom: (_entryType == 'long_term' && _validFrom != null)
            ? d(_validFrom!)
            : null,
        validTo: (_entryType == 'long_term' && _validTo != null)
            ? d(_validTo!)
            : null,
        visitDays: (_entryType == 'multiple' && _visitDays.isNotEmpty)
            ? _visitDays.map(d).toList()
            : null,
        timeWindow: (_entryType == 'multiple' &&
                _timeWindowController.text.trim().isNotEmpty)
            ? _timeWindowController.text.trim()
            : null,
      );

      await ref.read(visitorRepositoryProvider).createVisitor(visitor);
      await ref.read(myVisitorsProvider.notifier).refresh();

      if (mounted) {
        // Boss feedback 15/07: once the pass is created, the form starts
        // fresh — no leftover data from the previous visitor.
        setState(() {
          _nameController.clear();
          _typeController.clear();
          _dateController.clear();
          _plateController.clear();
          _timeWindowController.clear();
          _selectedDateTime = null;
          _entryType = 'single';
          _validFrom = null;
          _validTo = null;
          _visitDays.clear();
        });
        ref.read(accessTabIndexProvider.notifier).state =
            1; // Switch to passes tab
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(e.toString()), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isSubmitting = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final tabIndex = ref.watch(accessTabIndexProvider);

    return Scaffold(
      backgroundColor: AppColors.backgroundGrey,
      body: GradientBackground(
        child: SafeArea(
          child: Column(
            children: [
              Padding(
                padding: const EdgeInsets.fromLTRB(24, 32, 24, 24),
                child: _buildHeader(context),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 24),
                child: _buildSegmentedControl(tabIndex),
              ),
              const SizedBox(height: 24),
              Expanded(
                child: IndexedStack(
                  index: tabIndex,
                  children: [
                    _buildPreRegisterForm()
                        .animate(target: tabIndex == 0 ? 1 : 0)
                        .fade(duration: 300.ms)
                        .slideY(begin: 0.1, end: 0),
                    _buildActivePasses()
                        .animate(target: tabIndex == 1 ? 1 : 0)
                        .fade(duration: 300.ms)
                        .slideY(begin: 0.1, end: 0),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildHeader(BuildContext context) {
    final profileAsync = ref.watch(currentProfileProvider);
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: const [
            Text(
              'Visitor Access',
              style: TextStyle(
                fontSize: 28,
                color: AppColors.textPrimary,
                fontWeight: FontWeight.w800,
                letterSpacing: -0.5,
              ),
            ),
            SizedBox(height: 2),
            Text(
              'Pre-register guests & manage passes',
              style: TextStyle(
                fontSize: 13.5,
                color: AppColors.textSecondary,
                fontWeight: FontWeight.w500,
              ),
            ),
          ],
        ),
        GestureDetector(
          onTap: () => context.push('/profile'),
          child: Container(
            width: 46,
            height: 46,
            padding: const EdgeInsets.all(2.5),
            decoration: const BoxDecoration(
              shape: BoxShape.circle,
              gradient: AppColors.brandGradient,
            ),
            child: ClipOval(
              child: Container(
                color: AppColors.primaryWhite,
                child: profileAsync.when(
                  data: (profile) => profile?.avatarUrl != null
                      ? CachedNetworkImage(
                          imageUrl: profile!.avatarUrl!,
                          fit: BoxFit.cover,
                          placeholder: (_, __) => const Center(
                            child: SizedBox(
                              width: 18,
                              height: 18,
                              child: CircularProgressIndicator(strokeWidth: 2),
                            ),
                          ),
                          errorWidget: (_, __, ___) => const Icon(
                            PhosphorIconsRegular.user,
                            color: AppColors.brand,
                          ),
                        )
                      : const Icon(
                          PhosphorIconsRegular.user,
                          color: AppColors.brand,
                        ),
                  loading: () => const Center(
                    child: SizedBox(
                      width: 18,
                      height: 18,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    ),
                  ),
                  error: (_, __) => const Icon(
                    PhosphorIconsRegular.user,
                    color: AppColors.brand,
                  ),
                ),
              ),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildSegmentedControl(int currentIndex) {
    return Container(
      padding: const EdgeInsets.all(5),
      decoration: BoxDecoration(
        color: AppColors.primaryWhite,
        borderRadius: BorderRadius.circular(18),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFF6A7BA8).withOpacity(0.10),
            blurRadius: 20,
            offset: const Offset(0, 8),
          ),
        ],
      ),
      child: Row(
        children: [
          Expanded(child: _buildSegmentButton(0, 'Pre-Register', currentIndex)),
          Expanded(
            child: _buildSegmentButton(1, 'Active Passes', currentIndex),
          ),
        ],
      ),
    );
  }

  Widget _buildSegmentButton(int index, String label, int currentIndex) {
    final isSelected = index == currentIndex;
    return GestureDetector(
      onTap: () => ref.read(accessTabIndexProvider.notifier).state = index,
      behavior: HitTestBehavior.opaque,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        padding: const EdgeInsets.symmetric(vertical: 12),
        decoration: BoxDecoration(
          gradient: isSelected ? AppColors.brandGradient : null,
          borderRadius: BorderRadius.circular(14),
          boxShadow: isSelected
              ? [
                  BoxShadow(
                    color: AppColors.brand.withOpacity(0.30),
                    blurRadius: 12,
                    offset: const Offset(0, 6),
                  ),
                ]
              : [],
        ),
        child: Center(
          child: Text(
            label,
            style: TextStyle(
              fontSize: 14,
              fontWeight: isSelected ? FontWeight.w700 : FontWeight.w600,
              color: isSelected ? Colors.white : AppColors.textSecondary,
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildEntryTypeSelector() {
    const opts = [
      ('single', 'Single', PhosphorIconsRegular.calendarDot),
      ('multiple', 'Multiple', PhosphorIconsRegular.calendarDots),
      ('long_term', 'Long term', PhosphorIconsRegular.calendarPlus),
    ];
    return Row(
      children: [
        for (final o in opts) ...[
          Expanded(
            child: GestureDetector(
              onTap: () => setState(() => _entryType = o.$1),
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 180),
                padding: const EdgeInsets.symmetric(vertical: 12),
                decoration: BoxDecoration(
                  gradient: _entryType == o.$1 ? AppColors.brandGradient : null,
                  color: _entryType == o.$1 ? null : AppColors.surfaceTint,
                  borderRadius: BorderRadius.circular(14),
                ),
                child: Column(
                  children: [
                    Icon(
                      o.$3,
                      size: 18,
                      color: _entryType == o.$1
                          ? Colors.white
                          : AppColors.textSecondary,
                    ),
                    const SizedBox(height: 4),
                    Text(
                      o.$2,
                      style: TextStyle(
                        fontSize: 11.5,
                        fontWeight: FontWeight.w700,
                        color: _entryType == o.$1
                            ? Colors.white
                            : AppColors.textSecondary,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
          if (o.$1 != 'long_term') const SizedBox(width: 8),
        ],
      ],
    );
  }

  Widget _dateField(
    String label,
    DateTime? value,
    ValueChanged<DateTime> onPick,
  ) {
    final ctrl = TextEditingController(
      text: value == null ? '' : DateFormat('MMM d, yyyy').format(value),
    );
    return GestureDetector(
      onTap: () async {
        final now = DateTime.now();
        final d = await showDatePicker(
          context: context,
          initialDate: value ?? now,
          firstDate: now.subtract(const Duration(days: 1)),
          lastDate: now.add(const Duration(days: 365)),
        );
        if (d != null) onPick(d);
      },
      behavior: HitTestBehavior.opaque,
      child: AbsorbPointer(
        child: GlassTextField(
          controller: ctrl,
          hintText: label,
          prefixIcon: PhosphorIconsRegular.calendar,
        ),
      ),
    );
  }

  Widget _buildMultiDayPicker() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        OutlinedButton.icon(
          onPressed: () async {
            final now = DateTime.now();
            final d = await showDatePicker(
              context: context,
              initialDate: now,
              firstDate: now.subtract(const Duration(days: 1)),
              lastDate: now.add(const Duration(days: 365)),
            );
            if (d != null && !_visitDays.any((x) => x.day == d.day && x.month == d.month && x.year == d.year)) {
              setState(() => _visitDays.add(d));
            }
          },
          icon: const Icon(PhosphorIconsRegular.plus, size: 16),
          label: const Text('Add a day'),
        ),
        if (_visitDays.isNotEmpty)
          Padding(
            padding: const EdgeInsets.only(top: 8),
            child: Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                for (final d in _visitDays)
                  Chip(
                    label: Text(DateFormat('MMM d').format(d)),
                    onDeleted: () => setState(() => _visitDays.remove(d)),
                  ),
              ],
            ),
          ),
      ],
    );
  }

  Widget _buildPreRegisterForm() {
    return SingleChildScrollView(
      padding: const EdgeInsets.fromLTRB(24, 0, 24, 120),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          PremiumCard(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const SectionHeader(
                  title: 'Guest details',
                  subtitle: 'We will generate a QR pass for entry',
                ),
                const SizedBox(height: 18),
                GlassTextField(
                  controller: _nameController,
                  hintText: 'Visitor Name',
                  prefixIcon: PhosphorIconsRegular.user,
                ),
                const SizedBox(height: 16),
                GlassTextField(
                  controller: _typeController,
                  hintText: 'Purpose (e.g. Guest, Delivery)',
                  prefixIcon: PhosphorIconsRegular.tag,
                ),
                const SizedBox(height: 16),
                // HCA point 7: choose the pass type. PHH keeps single-visit.
                ...[
                  _buildEntryTypeSelector(),
                  const SizedBox(height: 16),
                ],
                if (_entryType == 'single')
                  GestureDetector(
                    onTap: _pickDateTime,
                    behavior: HitTestBehavior.opaque,
                    child: AbsorbPointer(
                      child: GlassTextField(
                        controller: _dateController,
                        hintText: 'Date & Time (Optional)',
                        prefixIcon: PhosphorIconsRegular.calendar,
                      ),
                    ),
                  ),
                if (_entryType == 'long_term') ...[
                  _dateField(
                    'Valid From',
                    _validFrom,
                    (d) => setState(() => _validFrom = d),
                  ),
                  const SizedBox(height: 16),
                  _dateField(
                    'Valid Until',
                    _validTo,
                    (d) => setState(() => _validTo = d),
                  ),
                ],
                if (_entryType == 'multiple') ...[
                  _buildMultiDayPicker(),
                  const SizedBox(height: 16),
                  GestureDetector(
                    onTap: _pickTimeWindow,
                    behavior: HitTestBehavior.opaque,
                    child: AbsorbPointer(
                      child: GlassTextField(
                        controller: _timeWindowController,
                        hintText: 'Time window — tap to pick',
                        prefixIcon: PhosphorIconsRegular.clock,
                      ),
                    ),
                  ),
                ],
                const SizedBox(height: 16),
                GlassTextField(
                  controller: _plateController,
                  hintText: 'Vehicle Plate (Optional)',
                  prefixIcon: PhosphorIconsRegular.carProfile,
                ),
              ],
            ),
          ),
          const SizedBox(height: 24),
          _isSubmitting
              ? const Center(
                  child: CircularProgressIndicator(color: AppColors.brand),
                )
              : ActionButton(
                  label: 'Generate Pass',
                  onPressed: _submitForm,
                  backgroundColor: AppColors.brand,
                  icon: PhosphorIconsRegular.qrCode,
                ),
        ],
      ),
    );
  }

  Widget _buildActivePasses() {
    final visitorsAsync = ref.watch(myVisitorsProvider);

    return visitorsAsync.when(
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, stack) => AppErrorState(
        message: 'Error: $error',
        onRetry: () => ref.read(myVisitorsProvider.notifier).refresh(),
      ),
      data: (visitors) {
        // Show only active passes (not yet checked-out)
        final activeVisitors = visitors
            .where((v) => v.status != 'checked_out' && v.qrToken != null)
            .toList();

        if (activeVisitors.isEmpty) {
          return AppEmptyState(
            icon: PhosphorIconsRegular.qrCode,
            title: 'No active passes',
            message: 'Pre-register a guest to generate a visitor QR pass.',
            gradient: AppColors.skyGradient,
            actionLabel: 'Pre-register a guest',
            onAction: () => ref.read(accessTabIndexProvider.notifier).state = 0,
          );
        }

        return ListView.separated(
          padding: const EdgeInsets.fromLTRB(24, 0, 24, 120),
          itemCount: activeVisitors.length,
          separatorBuilder: (context, index) => const SizedBox(height: 16),
          itemBuilder: (context, index) {
            final visitor = activeVisitors[index];
            final dateStr = visitor.expectedAt != null
                ? DateFormat(
                    'MMM d, yyyy HH:mm',
                  ).format(DateTime.parse(visitor.expectedAt!).toLocal())
                : 'Walk-in';

            // HCA: describe the pass validity on the card (boss feedback).
            String? passType;
            {
              String day(String iso) {
                try {
                  return DateFormat('MMM d').format(DateTime.parse(iso));
                } catch (_) {
                  return iso;
                }
              }

              switch (visitor.entryType) {
                case 'multiple':
                  final days = (visitor.visitDays ?? []).map(day).join(', ');
                  passType =
                      'Multiple days${days.isEmpty ? '' : ': $days'}'
                      '${visitor.timeWindow == null ? '' : ' • ${visitor.timeWindow}'}';
                  break;
                case 'long_term':
                  final from = visitor.validFrom;
                  final to = visitor.validTo;
                  passType =
                      'Long term'
                      '${from != null ? ': ${day(from)}' : ''}'
                      '${to != null ? ' – ${day(to)}' : ''}';
                  break;
                default:
                  passType = 'Single entry';
              }
            }

            return VisitorPassCard(
              name: visitor.visitorName,
              type: visitor.purpose,
              time: dateStr,
              qrData: visitor.qrToken!,
              status: visitor.status,
              passType: passType,
            );
          },
        );
      },
    );
  }
}
